### PR TITLE
Add a starting point features to the project

### PR DESCRIPTION
**Pull request by TheRealOne78**
I've added the following starting point features:
- Copyright comments for every source code file, at the beggining of each file;
- A signal handler function that handles `SIGINT` and `SIGTERM`;
- An implementation of the GNU getopt_long function. GNU Getopt is part of the GNU C Library which is released under the LGPL license. It permits to use this along with code licensed under the MIT terms;
- `printf_version()` to print the version and copyright notices when adding the `-v` or `--version` argument;
- `printf_version()` to print a help list when adding the `-h` or `--help` argument.

*NOTE: duplicate of #4.

### CODE REVIEW

**Comment by Maks1116** [comment]
I think that instead of prompting user if they really want to quit, we should perform shutdown immediately after receiving signal.

**Comment by Ariimeow78** [comment]
> I think that instead of prompting user if they really want to quit, we should perform shutdown immediately after receiving signal.

Yes, that's an idea.. tho we can't really implement yet a shutdown if we don't have what to shutdown, so leaving this handler like this with a TODO comment for the future might be a better approach than removing the function completely. Gonna do that

**Comment by Maks1116** [comment]
> > I think that instead of prompting user if they really want to quit, we should perform shutdown immediately after receiving signal.
> 
> Yes, that's an idea.. tho we can't really implement yet a shutdown if we don't have what to shutdown, so leaving this handler like this with a TODO comment for the future might be a better approach than removing the function completely. Gonna do that

It would be useful for example for closing logger file output stream on shutdown.

**Comment by Ariimeow78** [comment]
Yes, that's indeed great! But I'd suggest to make a shutdown method first, an API that can be called to set stuff that needs safe shutdown and can be easily shutdown in just one call by the signal handler.
Things like file streams, asynchronous processes, etc to be accessible in one method for shutdown.

**Comment by Ariimeow78** [comment]
BTW, I did add more files and I don't know how to add them in cmake. Can you do that please?

**Comment by Maks1116** [comment]
> BTW, I did add more files and I don't know how to add them in cmake. Can you do that please?

There's no need to add anything to cmake. It will be used when it is included by something else. By the way, you might want to remove that `main.out` file.

**Comment by Ariimeow78** [comment]
> There's no need to add anything to cmake. It will be used when it is included by something else.

You don't need to add the other c files?

> By the way, you might want to remove that main.out file.

Facepalm

**Comment by Maks1116** [comment]
> > There's no need to add anything to cmake. It will be used when it is included by something else.
> 
> You don't need to add the other c files?

Oh, wait apparently my compiler is so special, that it can compile it once and then fail doing so. I'm going to CMakeLists for that in a few minutes.

**Pull request merged**
